### ISSUE TITLE
Getting progress on upload.

### ISSUE THREAD

**Issue by TomSchillemans** [janko-m/paperclip-dropbox#56]
This isn't really and issue, but It obviously takes a little while for a picture to be uploaded to dropbox. 
For user experience's sake I would like to display an progress bar. Is it possible to do so?

**Comment by janko-m** [comment]
Well, Paperclip itself doesn't have that API, so it's not really possible for paperclip-dropbox either, since I'm just providing a storage extension. You meant server-side progress bar (in Ruby) or client-side (in HTML/JavaScript)? For the latter I highly recommend [Refile](https://github.com/refile/refile); it's the new uploading solution in Ruby which does things right, although it doesn't have a Dropbox extension yet.

**Comment by TomSchillemans** [comment]
thanks for the quick reply! I user Paperclip with file system storage and that is near instant so I don't really need an progress bar for that, how ever loading images from file system does take a while with paperclip. I don't know if it is just paperclip or if the problem lies within the fact it is file system. 

On a side node. I configure paperclip-dropbox with use an .env file, it is working however loading the home page takes a whole lot of time. I did it without it (specifying the variables within de dropbox.yml) and it is instantaneously.

**Comment by janko-m** [comment]
Ok, I guess I'll close this, since any progress bars should be done in Paperclip itself.
